### ISSUE TITLE
Runbook - Limits error: 50 compute environments

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-docs#1]
### RUNBOOK Limits Error : Only 50 Compute Environments allowed

**Symptom**: This error occurs when you have too many feature branches of cirrus, as they will spin up compute environments and other AWS infrastructure.

**Resolution**: This is current a hard limit per account; you cannot request an increase with AWS support to allow for more compute environments using the support tab.

For immediate resolution, you can delete feature branch cloudformation templates, which will delete all of the infrastructure managed by the Serverless framework associated with a feature branch of cirrus. Click the Cloudformation tab and select a feature branch that is no longer needed, then click Delete image

Once it deletes, it will fail in the state of DELETE_FAILED. This is because it's trying to delete S3 buckets that have data in them, a pretty annoying aspect of Serverless.

Navigate to the resources it's complaining about and empty the bucket, then delete the bucket. Then you should be able to go back to the Cloudformation page, click the DELETE_FAILED stack, delete it again, and it will be fully removed.

**Moving forward**:
In general, ensure that all your compute environments are in use, and remove any un-used built-in environments, if necessary.

**Comment by jkeifer** [comment]
Archiving repo, closing this issue. Moved to https://github.com/cirrus-geo/cirrus-geo/issues/269.
