### ISSUE TITLE
Runbook -  Step functions are not being spun up as expected (state database fix)

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-docs#2]
### RUNBOOK Step functions are not being spun up as expected (state database fix)
**Symptom**: You've run a job that returned matches from the feeder, but no step functions were created.

**Resolution**: Check the DynamoDB state database. If the state is `SUCCESSFUL`, you can override this (and rerun it) by adding "replace": true to your process block definition.

If you search for the ID and it's stuck in `PROCESSING`, the above solution won't work. You need to delete the ID from the item table. This is a safer operation than it may seem; it doesn't delete the data, and worst case it'll re-run it if it is requested again.

> Note, the state database is unique per feature branch

In the AWS console, navigate to the DynamoDB page. Under Tables, click Explore items
> TODO: Add image

Search for your ID in question: Attribute name: `itemids` Value: `<the ID>`
> TODO: Add image

Tick the checkbox and click delete. This removes it and allows the ID to be run again.

**Comment by jkeifer** [comment]
Archiving repo, closing this issue. Moved to https://github.com/cirrus-geo/cirrus-geo/issues/269.
