### ISSUE TITLE
Runbook - Stalled jobs, hanging ec2 instances after large runs

### ISSUE THREAD

**Issue by stark525** [cirrus-geo/cirrus-docs#3]
### RUNBOOK Stalled jobs after large batch runs

**Symptom**: After running large, it's possible some jobs appear "stuck". There will be EC2 instances that are associated with batch tasks that are hanging.

**Resolution**: Since all jobs are configured to retry by default, you can safely terminate the EC2 instances that are running the batch jobs, which will trigger a new instance to try again.

> Note: This is assuming you ran overnight and no other jobs are running!
> TODO: Add image

Make sure to filter the EC2 instances to `cirrus-main` and `Batch`. Select them all -> Instance State -> Terminate. New instances should replace them.

**Comment by jkeifer** [comment]
Archiving repo, closing this issue. Moved to https://github.com/cirrus-geo/cirrus-geo/issues/269.
